### ISSUE TITLE
Cards won't scroll on mobile

### ISSUE THREAD

**Issue by mohsenkhanpour** [zzseba78/Kick-Off#10]
Cards template is so hard to scroll on mobile browsers.
If you touch outside of the card section you are able to scroll, however as cards take most of the space, when you touch the card itself to scroll nothing happens.

I don't know if this a problem on UI-Kit behalf or the template is designed that way. If it is a bug on UI-Kit behalf we should let them know.

**Comment by mohsenkhanpour** [comment]
According to @aarongerig on UIKit Gitter:

>  That's because the cards can be sorted (sortable component). So it's a problem on behalf of the template, not UIkit.

**Comment by mohsenkhanpour** [comment]
It seems it is possible to scroll by grabbing the photos in iOS, however on Android it doesn't happen.

**Comment by zzseba78** [comment]
Hi @mohsenkhanpour ! Thanks for your feedback.
Seems that it´s an issue with the Sortable component, it´s implemented with a Handle (https://getuikit.com/docs/sortable#handle), and **it should scroll unless you position over the drag icon**. It works perfect on IOS and Hight Sierra but seems that doesn´t work properly on Android.

I test it on Android and you are right, and test it in the docs and it doesn´t scroll either.
I created an Issue with this https://github.com/uikit/uikit/issues/3536
