### ISSUE TITLE
Blog - navbar

### ISSUE THREAD

**Issue by eydun** [zzseba78/Kick-Off#11]
The navbar in the blog looks "sliced" at the bottom when viewed with Firefox.

![billede](https://user-images.githubusercontent.com/12867/44313180-92370c00-a3fb-11e8-819c-08fb6e797dd0.png)

**Comment by zzseba78** [comment]
I think it was a spacing issue with the hack of hide the scroll from the subnav. Try now please.

**Comment by eydun** [comment]
Perfect!

**Comment by zzseba78** [comment]
Nice!!
