### ISSUE TITLE
enhancement request on the card grid layout with a search filter 

### ISSUE THREAD

**Issue by viseth** [zzseba78/Kick-Off#15]
Hi Sebastian,

Thanks for this great boostrap kit, awesome ! I'm testing the card layout one and was wondering whether you could add this functionality to it:
basically be able to filter out the cards based on the search pattern entered in the search box. It would add great value to this kit.

![github](https://user-images.githubusercontent.com/1708388/51833292-50d65100-22f7-11e9-87f1-0c25fe209a02.png)

Many thanks,
Regards,

Viseth

**Comment by zzseba78** [comment]
Hi @viseth , thank you for your kind words!

This is a great idea! I will check it out next week, i saw a working codepen some weeks ago with this search applied to filters, so we have a starting point there.

I will let you know when ready!

**Comment by zzseba78** [comment]
@viseth Check this out! :)
Now it search on `data-tags` on each card, that can contain title and tags content.
https://zzseba78.github.io/Kick-Off/cards.html

**Comment by viseth** [comment]
@zzseba78 Waouh ! great job it works perfectly :-) .
What about the idea of clicking on a view icon at the bottom right corner to display the image with the info details of it in a modal dialog box ?

Many thanks,
Regards,

Viseth

**Comment by zzseba78** [comment]
Hi @viseth . Yes, i was thinking about change card distrubutions, looks little confusing now, remove some social, remove drag functionality maybe, and put a preview of the image, lightbox or modal.

Next week i will work it! Have a nice day.

**Comment by viseth** [comment]
Hi @zzseba78 ! I vote for a modal to change from the usual lightbox preview maybe and to later allows the user to update the image details for example.

I'll keep an eye on your update :-)

Many thanks,
And have a nice week-end !
