### ISSUE TITLE
ENHANCEMENT REQUEST : page with status tiles 

### ISSUE THREAD

**Issue by viseth** [zzseba78/Kick-Off#19]
Hi Sebastian,

Thanks for the good work and giving dev guys a starter tool kit to get started!
It would be nice to have an admin page with tiles that changes color with the ability to increase or decrease the size of the tiles using a drag button. This would come in a masonry fashion.
Another button would allow a different display: instead of tiles, it would the tile would be instead displayed line by line.
Do you think that could be something your could add to the starter toolkit ?

Here's an exemple 👍 

![ulkit3-2](https://user-images.githubusercontent.com/1708388/59699463-e6fd0c00-91f1-11e9-8f90-ca9ad58cf85e.JPG)

Let me know if it makes sense, 

Cheers,

**Comment by zzseba78** [comment]
Hi @viseth , thanks for your kind words.
In concern of your idea, i think this is a very specific use case, and this project points to general purpose layouts, so i don´t think this layout would be included in the set.
Have a nice day!
