### ISSUE TITLE
expandable sidebar

### ISSUE THREAD

**Issue by AlbanMinassian** [zzseba78/Kick-Off#9]
Hello, 

About [dashboard](https://zzseba78.github.io/Kick-Off/dashboard.html): is it possible to have a sidebar like this [https://foundation.zurb.com/building-blocks/blocks/app-dashboard-layout.html](https://foundation.zurb.com/building-blocks/blocks/app-dashboard-layout.html) with uikit3 ?

Thanks 
ami44

**Comment by zzseba78** [comment]
Yes it is. It will require that you create some custom css, the default bar and some modifier class to shrink the bar and hide the items text. You can toggle the modifier css class with a button and Toggle component.
